### ISSUE TITLE
New dashboard from hub to builder error

### ISSUE THREAD

**Issue by alainbodiguel** [gisaia/ARLAS-wui-hub#149]
When I choose to create a new dashboard from the hub within an organisation (not my private one), I get sent to the builder on the dashboard selection page with my private org selected by default, which is not the expected behaviour.

**Comment by sebbousquet** [comment]
Fix by https://github.com/gisaia/ARLAS-wui-hub/commit/d0161897a960bae659b048147ee4e94d97375032
