### ISSUE TITLE
Filters on the collection are not kept after opening a dashboard

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui-hub#172]
After opening a dashboard, since the list is refreshed, if the user clicked on the collections on the side before, all dashboards will be displayed, but the filters will be kind of remembered even though it will not display as such.

For example, I have collections A, B and C. I select collection A, and click on the related dashboard. i come back on the hub, all dashboards are shown. I click on collection B, I get only dashboards of collection A.

**Comment by MohamedHamouGisaia** [comment]
@QuCMGisaia I noticed this bug and fixed already in the feat/25.0.0 branch
I didn't create a ticket for that though ! Many thanks
