### ISSUE TITLE
Wrong error message when I try to duplicate a config with no rights to write

### ISSUE THREAD

**Issue by mbarbet** [gisaia/ARLAS-wui-hub#51]
Link to https://github.com/gisaia/ARLAS-wui-toolkit/issues/389

**Comment by sebbousquet** [comment]
Resolved in gisaia/ARLAS-wui-toolkit#389.
Close when arlas-wui-toolkit will be released

**Comment by sebbousquet** [comment]
Closed with the release of  [arlas-wui-toolkit 14.1.0](https://github.com/gisaia/ARLAS-wui-toolkit/blob/develop/CHANGELOG.md#v1410-2020-12-07)
